/*
 * Climb.cpp
 *
 *  Created on: Feb 7, 2017
 *      Author: josie
 */

#include <iostream>
#include "Climb.h"
#include "../OI.h"
#include "../Robot.h"


Climb::Climb(): Command() {
        // Use requires() here to declare subsystem dependencies
	Requires(Robot::climb.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void Climb::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void Climb::Execute() {
	float trigger_value = Robot::oi->GetAxisValue(Robot::oi->getRobotOperator(), OI::Xbox_Axis_Right_Trigger);

	if (trigger_value != 0) {
		Robot::climb->climb_start(1);	//go at full speed when the right trigger is pressed
	}
	else {
		Robot::climb->climb_start(0.25);	//go at half speed when the right trigger is not pressed
	}

}

// Make this return true when this Command no longer needs to run execute()
bool Climb::IsFinished() {
    if (Robot::oi->getClimbButton()->Get())
    return false;
    return true;
}

// Called once after isFinished returns true
void Climb::End() {
	Robot::climb->climb_stop();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void Climb::Interrupted()
{

}
