/*
 * ClimbStop.cpp
 *
 *  Created on: Feb 9, 2017
 *      Author: josie
 */

#include <iostream>
#include "ClimbStop.h"
#include "../OI.h"
#include "../Robot.h"


ClimbStop::ClimbStop(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void ClimbStop::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void ClimbStop::Execute() {
	Robot::climb->climb_start();

}

// Make this return true when this Command no longer needs to run execute()
bool ClimbStop::IsFinished() {
    return true;
}

// Called once after isFinished returns true
void ClimbStop::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ClimbStop::Interrupted() {

}


