#include "Vent_On.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

Vent_On::Vent_On(): InstantCommand() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
	Requires(Robot::gearholder.get());
}

// Called just before this Command runs the first time
void Vent_On::Initialize() {
	Robot::gearholder->Vent_On();
}

