#include "Vent.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

Vent::Vent(): InstantCommand() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
	Requires(Robot::gearholder.get());
}

// Called just before this Command runs the first time
void Vent::Initialize() {
	Robot::gearholder->Vent();
}

