#include "Vent_Off.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

Vent_Off::Vent_Off(): InstantCommand() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
	Requires(Robot::gearholder.get());
}

// Called just before this Command runs the first time
void Vent_Off::Initialize() {
	Robot::gearholder->Vent_Off();
}

