// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
#include "CANTalon.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<CANTalon> RobotMap::driveTrainLeft1;
std::shared_ptr<CANTalon> RobotMap::driveTrainRight2;
std::shared_ptr<CANTalon> RobotMap::driveTrainRight1;
std::shared_ptr<CANTalon> RobotMap::driveTrainLeft2;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<DoubleSolenoid> transmissionShifterSolenoid1;
std::shared_ptr<DoubleSolenoid> transmissionShifterSolenoid2;

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    LiveWindow *lw = LiveWindow::GetInstance();

    driveTrainLeft1.reset(new CANTalon(1));
    lw->AddActuator("DriveTrain", "Left1", driveTrainLeft1);
    
    driveTrainRight2.reset(new CANTalon(4));
    lw->AddActuator("DriveTrain", "Right2", driveTrainRight2);
    
    driveTrainRight1.reset(new CANTalon(3));
    lw->AddActuator("DriveTrain", "Right1", driveTrainRight1);
    
    driveTrainLeft2.reset(new CANTalon(2));
    lw->AddActuator("DriveTrain", "Left2", driveTrainLeft2);
    
    transmissionShifterSolenoid1.reset(new DoubleSolenoid(0, 1));
    lw->AddActuator("Transmission", "ShifterSolenoid", transmissionShifterSolenoid1);

    transmissionShifterSolenoid2.reset(new DoubleSolenoid(2, 3));
    lw->AddActuator("Transmission", "ShifterSolenoid", transmissionShifterSolenoid2);
    

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
