// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
#include "CANTalon.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "DoubleSolenoid.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<CANTalon> RobotMap::driveTrainLeft1;
std::shared_ptr<CANTalon> RobotMap::driveTrainRight2;
std::shared_ptr<CANTalon> RobotMap::driveTrainRight1;
std::shared_ptr<CANTalon> RobotMap::driveTrainLeft2;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<frc::DoubleSolenoid> RobotMap::transmissionShifterSolenoid;
std::shared_ptr<CANTalon> RobotMap::intakeMotor;
std::shared_ptr<frc::Solenoid> RobotMap::extenderSolenoid;
std::shared_ptr<frc::Solenoid> RobotMap::ventSolenoid;
std::shared_ptr<CANTalon> RobotMap::shooterTalon1;
std::shared_ptr<CANTalon> RobotMap::shooterTalon2;
std::shared_ptr<CANTalon> RobotMap::gateTalon;
std::shared_ptr<Pixy> RobotMap::pixy;
std::shared_ptr<AHRS> RobotMap::imu;

std::shared_ptr<CANTalon> RobotMap::climberMotor;


void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    frc::LiveWindow *lw = frc::LiveWindow::GetInstance();

    driveTrainLeft1.reset(new CANTalon(1));
    lw->AddActuator("DriveTrain", "Left1", driveTrainLeft1);
    
    driveTrainRight2.reset(new CANTalon(4));
    lw->AddActuator("DriveTrain", "Right2", driveTrainRight2);
    
    driveTrainRight1.reset(new CANTalon(3));
    lw->AddActuator("DriveTrain", "Right1", driveTrainRight1);
    
    driveTrainLeft2.reset(new CANTalon(2));
    lw->AddActuator("DriveTrain", "Left2", driveTrainLeft2);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    imu.reset(new AHRS(frc::SPI::Port::kMXP));
    lw->AddSensor("Sensor","IMU",imu);

    transmissionShifterSolenoid.reset(new frc::DoubleSolenoid(0, 1));
    lw->AddActuator("Transmission", "ShifterSolenoid", transmissionShifterSolenoid);
    
    intakeMotor.reset(new CANTalon(5));
    lw->AddActuator("Intake", "intakeMotor", intakeMotor);

    extenderSolenoid.reset(new frc::Solenoid(3));
    lw->AddActuator("GearHolder", "extenderSolenoid", extenderSolenoid);

    ventSolenoid.reset(new frc::Solenoid(4));
    lw->AddActuator("GearHolder", "gearSolenoid2", ventSolenoid);

    shooterTalon1.reset(new CANTalon(7));
    lw->AddActuator("Shooter", "shooterTalon1", shooterTalon1);

    shooterTalon2.reset(new CANTalon(8));
    lw->AddActuator("Shooter", "shooterTalon2", shooterTalon2);

    gateTalon.reset(new CANTalon(6));
    lw->AddActuator("GateKeeper", "gateTalon", gateTalon);

    pixy.reset(new Pixy(0x54));

    climberMotor.reset(new CANTalon(10));
    lw->AddActuator("Climber", "climberMotor", climberMotor);
}
