// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef GEARHOLDER_H
#define GEARHOLDER_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class GearHolder: public Subsystem {
public:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	GearHolder();
	void InitDefaultCommand();
	void Configuration();

	void PushGearHolder();
	void PullGearHolder();

private:
	std::shared_ptr<Solenoid> gearSolenoid1;
	std::shared_ptr<Solenoid> gearSolenoid2;
};

#endif
