// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef SHOOTERPIXY_H
#define SHOOTERPIXY_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "../Pixy.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class ShooterPixy: public Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities

	std::shared_ptr<Pixy> pixy;

public:
	ShooterPixy();
	void InitDefaultCommand();

	uint16_t BlockArea(uint16_t height, uint16_t width);	//calculates the area of a block
	uint16_t * Get_Largest_Block_XY();	//return an array with the x and y values of the largest block
	bool OnTarget(); //checks if shooter is directly facing the target (boiler)
	float Distance_From_Target(); //uses trig to check how far the shooter is from the target (boiler)

};

#endif
